exclude: (^\.pixi/|.snap)
repos:
  - repo: local
    hooks:
      - id: typos
        name: typos
        entry: pixi run -e lint typos --write-changes --force-exclude
        language: system
        types: [text]
  - repo: local
    hooks:
      - id: tex-fmt
        name: tex-fmt
        entry: pixi run -e lint tex-fmt
        language: system
        types: [tex]
